---
oracle_user: "oracle"
software_dir: "/u01/stage"
oracle_install_group: "oinstall"
root_dir: "/u02"
stage_dir: "/u02/stage"
grid_home: /u02/app/21.3.0/grid
grid_base: /u02/app/grid
asmi_name: "+ASM"
ASMI: "+ASM"
gridsetup_installer: "{{ grid_home }}/gridSetup.sh"
gi_rspfile:  gridsetup21c.rsp
grid_user: grid
root_user: root

#### SECTION A - BASIC ###########
ora_inventory: /u02/app/oraInventory
ora_language: en
install_option: CRS_SWONLY
oracle_base: /u02/app/oracle
oracle_home: /u02/app/21.3.0/grid

#### SECTION B - GROUPS ############
dba_grp: dba
oper_grp: dba
osasm_grp: dba

##### SECTION C - SCAN   ###########
scan_name: racdb01-scan
scan_port: 1521

#### SECTION D - CLUSTER & GNS  ########
ClusterConfigu_Type: STANDALONE
clusterName: racdb01
vscanName: "{{ vclusterName }}-scan"
vscanPort: 1521
node1_fq_hostname: rk8-oracle01.jtest.pivotal.io
node1_fq_vipname:  rk8-oracle01-vip.jtest.pivotal.io
node2_fq_hostname: rk8-oracle02.jtest.pivotal.io
node2_fq_vipname:  rk8-oracle02-vip.jtest.pivotal.io
node3_fq_hostname: rk8-oracle03.jtest.pivotal.io
node3_fq_vipname:  rk8-oracle03-vip.jtest.pivotal.io
networkInterfaceList: "{{ netdev2 }}:{{ network2 }}:1,{{ netdev0 }}:{{ network0 }}:5"
SYS_PASSWORD: changeme
# SYS_PASSWORD: Oracle123
SYSASMPassword: changeme
# SYSASMPassword: Oracle123
storage_Option: FLEX_ASM_STORAGE
dg_name: DATA
dg_redundancy: EXTERNAL
monitor_Password: Oracle123
ignore_DownNodes: false
mgt_Option: NONE
oms_Port: 0
execute_RootScript: false
asmdiskpre: /dev/oracleasm/disks/ASM_DISK0
disksWthFailGrp: '{{ asmdiskpre }}1,,{{ asmdiskpre }}2,,{{ asmdiskpre }}3,,{{ asmdiskpre }}4,,{{ asmdiskpre }}5,,{{ asmdiskpre }}6,'
asmdiskGroupdisks: '{{ asmdiskpre }}1,{{ asmdiskpre }}2,{{ asmdiskpre }}3,{{ asmdiskpre }}4,{{ asmdiskpre }}5,{{ asmdiskpre }}6'
dg_au: 1
asmdiskDiscoveryString: "/dev/oracleasm/disks"
disk_discstr: "/dev/oracleasm/disks/*"


_grid:
  ClusterConfigu_Type: STANDALONE
  clusterName: racdb01
  vscanName: "{{ clusterName }}-scan"
  vscanPort: 1521
  # node1_fq_hostname: rk8-oracle01.jtest.pivotal.io
  # node1_fq_vipname:  rk8-oracle01-vip.jtest.pivotal.io
  # node2_fq_hostname: rk8-oracle02.jtest.pivotal.io
  # node2_fq_vipname:  rk8-oracle02-vip.jtest.pivotal.io
  # node3_fq_hostname: rk8-oracle03.jtest.pivotal.io
  # node3_fq_vipname:  rk8-oracle03-vip.jtest.pivotal.io
  networkInterfaceList: "{{ netdev2 }}:{{ network2 }}:1,{{ netdev0 }}:{{ network0 }}:5"
  SYS_PASSWORD: "changeme"
  SYSASMPassword: "changeme"
  storage_Option: FLEX_ASM_STORAGE
  dg_name: DATA
  dg_redundancy: EXTERNAL
  monitor_Password: "changeme"
  ignore_DownNodes: false
  mgt_Option: NONE
  oms_Port: 0
  execute_RootScript: false
  domain: "jtest.pivotal.io"
  dev_group: /dev/rac
  asmdisks:
    - { name: "/dev/rac/crs1" }
    - { name: "/dev/rac/crs2" }
    - { name: "/dev/rac/crs3" }
    - { name: "/dev/rac/data" }
    - { name: "/dev/rac/fra" }
  asmdiskpre: /dev/oracleasm/disks/ASM_DISK0
  dg_au: 1
  asmdiskDiscoveryString: "/dev/oracleasm/disks"
  disk_discstr: "/dev/oracleasm/disks/*"

