---
- name: Copy Query Template Files
  become_user: "{{ _oracle.user }}"
  template: src={{ item.fn }}.j2 dest={{ item.copy_dir }}/{{ item.fn }} owner=oracle group=oinstall mode=0644 force=yes
  register: copy_query_files_templates
  with_items:
    - { fn: "change-password-system.sql", copy_dir: "{{ _oracle.home_dir }}" }
    - { fn: "enable-omf-autostart.sql", copy_dir: "{{ _oracle.home_dir }}" }
    - { fn: "grant-all-priv-oracleuser.sql", copy_dir: "{{ _oracle.home_dir }}" }
    - { fn: "create-oracleuser.sql", copy_dir: "{{ _oracle.home_dir }}" }
    - { fn: "create-user-table.sql", copy_dir: "{{ _oracle.home_dir }}" }
- debug: msg={{ copy_query_files_templates }}

