---
- name: Setup Oracle Database Installation Response File
  template: src={{ _oracle.rsp }}.rsp.j2 dest={{ _oracle.stage_dir }}/{{ _oracle.rsp }}.rsp mode=0755
  register: setup_oracle_db


- name: Changing Ownership, Group and Permissions
  file:
    path: "{{ item }}"
    owner: oracle
    group: oinstall
    recurse: yes
  register: change_permission
  with_items:
    - "{{ _oracle.home_dir }}"
    - "{{ _oracle.app_dir }}"
- debug: msg={{ change_permission }}


- name: Verify Oracle {{ oracle_version }} Database Software Pre-requisites
  become_user: "{{ _oracle.user }}"
  shell: |
    {{ _oracle.home_dir }}/runInstaller -executePrereqs -silent -responseFile {{ _oracle.stage_dir }}/{{ _oracle.rsp }}.rsp -noconfig -ignorePrereqFailure
  register: verify_oracle_db_prepared
  ignore_errors: true
  changed_when: verify_oracle_db_prepared.rc == 1 or verify_oracle_db_prepared.rc != 0
- debug: msg={{ verify_oracle_db_prepared }}


# -waitforcompletion -nowelcome -noconfig -debug -force -ignorePrereqFailure
# {{ _oracle.home_dir }}/runInstaller -silent -responseFile {{ _oracle.stage_dir }}/{{ _oracle.rsp }}.rsp -noconfig -ignorePrereqFailure
- name: Starting Installation of Oracle Database Software
  become_user: "{{ _oracle.user }}"
  shell: |
    export CV_ASSUME_DISTID=RHEL$(cat /etc/os-release | grep VERSION_ID | cut -d = -f 2 | sed 's/\"//g') ; \
    {{ _oracle.home_dir }}/runInstaller -silent -responseFile {{ _oracle.stage_dir }}/{{ _oracle.rsp }}.rsp -noconfig -waitforcompletion -ignorePrereqFailure
  register: command_output
- debug: msg={{ command_output }}
# shell: "export CV_ASSUME_DISTID=RHEL8.7 && {{ _oracle.home_dir }}/runInstaller -silent -responseFile {{ _oracle.stage_dir }}/{{ _oracle.rsp }}.rsp -noconfig -ignorePrereqFailure"


- name: Execute orainstroot.sh
  remote_user: "{{ _oracle.root_user }}"
  shell: |
    {{ _oracle.inventory }}/orainstRoot.sh
  register: execute_orainstroot
- debug: msg={{ execute_orainstroot }}


- name: Execute root.sh
  become_user: root
  shell: |
    {{ _oracle.home_dir }}/root.sh -silent
  register: execute_root_sh
- debug: msg={{ execute_root_sh }}

