---
#==================================================================================
# (1) Execute root.sh scripts on All Nodes
#==================================================================================

- name: Execute root.sh
  remote_user: "{{ root_user }}"
  shell: |
    {{ oracle_home }}/root.sh -silent > {{ stage_dir }}/dbsoftinstallroot.log
  register: racdbrootlog


- name: Output Log File Name
  remote_user: "{{ root_user }}"
  become_user: "{{ oracle_user }}"
  shell: |
    cat {{ stage_dir }}/dbsoftinstallroot.log | awk -v FS="(Check|for)" '{print $2}'
  register: loginfo


- set_fact:
    loginfo={{ loginfo.stdout }}


- name: Get root.sh Output for All Nodes
  shell: |
    cat {{ loginfo }}
  register: logdata


- debug: msg="{{ logdata.stdout_lines|map('trim')|list }}"


