---
#======================================================================================
#  Summary Steps:
#======================================================================================
# (1) Check if Binaries are Already Installed
# (2) Create Required Directories
# (3) Unpack Oracle 21c Database Software from the Local Drive
# (4) Create Silent Response File from Template
# (5) Install Oracle 21c Database Software for RAC
# (6) Execute root.sh on Primary Node and then Other Nodes
# (7) Remove Stage Directory
#======================================================================================

- name: Check OS ( Oracle RAC )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: pre, post, prepare, install, uninstall, add, setup, execute, remove, validate


- name: Display Pre Installation of Database Software Message
  debug:
    msg:
      - 'This Playbook is for Installing Oracle RAC Database Software 21c at {{ ansible_date_time.iso8601 }}:'
  tags: pre
  when: ( msg is defined and msg ==  true ) or ( rac_all is defined and rac_all == true )


- name: Pre Install Oracle RAC Database Software
  import_tasks: prepare-packages.yml
  tags: prepare
  when: ( pkgs is defined and pkgs ==  true ) or ( rac_all is defined and rac_all == true )


- name: Setup Oracle RAC Database Software
  import_tasks: setup-packages.yml
  tags: setup
  when: ( pkgs is defined and pkgs ==  true ) or ( rac_all is defined and rac_all == true )


- name: Execute Root.sh
  import_tasks: execute-root.yml
  tags: execute
  when: ( root is defined and root ==  true ) or ( rac_all is defined and rac_all == true )


- name: Verify Oracle RAC Database Software Installed
  tags: verify
  import_tasks: verify-database.yml
  when: ( db is defined and db ==  true ) or ( rac_all is defined and rac_all == true )


- name: Remove Stage Directory
  remote_user: "{{ root_user }}"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ stage_dir }}"
  tags: remove, install
  when: ( stage is defined and stage ==  true ) or ( rac_all is defined and rac_all == true )


- name: Display Post Install Message
  debug:
    msg:
      - 'This Steps completed below task for RAC database at {{ansible_date_time.iso8601}}:'
      - 'Install of Oracle 21c Oracle RAC Database Software task is completed successfully in Silent Mode'
  tags: post
  when: ( msg is defined and msg ==  true ) or ( rac_all is defined and rac_all == true )

