---
#==================================================================================================================================
# Summary Steps:
# (1) Create Silent Response File from Template
# (2) Install Oracle RAC Database 21.3.0 Software Only in Silent Mode
# (3) Validate Oracle Database Software Installation
#==================================================================================================================================

- name: Create Silent Response File from Template
  template: src={{ dbsoft21c_rsp }}.j2 dest={{ stage_dir }}/{{ dbsoft21c_rsp }} owner=oracle group=oinstall mode=0775
  when: inventory_hostname in groups['primary']


- name: Check if Binaries are Already Installed
  shell: grep "={{ oracle_home_name }}" {{ oracle_inventory }}/ContentsXML/inventory.xml
  register: dbsoft_install_check
  failed_when: false


- debug: msg="Installing Oracle Database Software - {{ oracle_home }}"
  when: oracle_home not in dbsoft_install_check.stdout_lines


- name: Install Oracle 21c Database Software
  remote_user: "{{ root_user }}"
  become_user: "{{ oracle_user }}"
  shell: |
    {{ oracle_home }}/runInstaller -ignorePrereq -waitforcompletion -silent \
    -responseFile {{ stage_dir }}/{{ dbsoft21c_rsp }} > /u02/stage/dbinstalloutput.log
  failed_when: racdbsoft_install_result.rc != 6                                         ## This condition is based on my setup
  register: racdbsoft_install_result
  when: inventory_hostname in groups['primary']
  # args:
  #    warn: false # set warn=false to prevent warning
  # no_log: true
- debug: msg={{ racdbsoft_install_result }}


- name: Get the Output Log Status
  remote_user: "{{ root_user }}"
  become_user: oracle
  shell: grep -r "Successfully Setup Software with *" /u02/stage/dbinstalloutput.log
  register: racdbsoftinstall_log
  when: inventory_hostname in groups['primary']


- name: Output from Post Database Software Installation Check
  debug:
    var: racdbsoftinstall_log.stdout
    verbosity: 0
  when: inventory_hostname in groups['primary'] and "'Successfully Setup Software.' or 'Successfully Setup Software with warning(s).' in racdbsoftinstall_log.stdout"

