---
# =================================================================================================================================================================
# Summary Steps:
# (1) Create Silent Response File from Template
# (2) Install Oracle RAC Database 21.3.0 Software Only in Silent Mode
# (3) Validate Oracle Database Software Installation
# =================================================================================================================================================================

- name: Create Silent Response File from Template
  template: src={{ dbsoft21c_rsp }}.j2 dest={{ stage_dir }}/{{ dbsoft21c_rsp }} owner=oracle group=oinstall mode=0775
  when: inventory_hostname in groups['ora_x1']


- name: Check if Binaries are Already Installed
  shell: grep "={{ oracle_home_name }}" {{ oracle_inventory }}/ContentsXML/inventory.xml
  register: dbsoft_install_check
  failed_when: false


- debug: msg="Installing Oracle Database Software - {{ oracle_home }}"
  when: oracle_home not in dbsoft_install_check.stdout_lines


- name: Install Oracle 21c Database Software
  remote_user: "{{ root_user }}"
  become: yes
  become_user: "{{ oracle_user }}"
  shell: |
    {{ oracle_home }}/runInstaller -ignorePrereq -waitforcompletion -silent -responseFile {{ stage_dir }}/{{ dbsoft21c_rsp }} > /u02/stage/dbinstalloutput.log
  failed_when: racdbsoft_install_result.rc != 6   #### This condition is based on my own setup
  register: racdbsoft_install_result
  when: inventory_hostname in groups['primary']
  # when: inventory_hostname in groups['ora_x1']
  # when: inventory_hostname in groups['ora_x1'] and oracle_home not in dbsoft_install_check.stdout_lines
  # args:
  #    warn: false # set warn=false to prevent warning
  # no_log: false
  # no_log: true
- debug: msg={{ racdbsoft_install_result }}


- name: Get the Output Log Status
  remote_user: "{{ root_user }}"
  become: yes
  become_user: oracle
  shell: grep -r "Successfully Setup Software with *" /u02/stage/dbinstalloutput.log
  register: racdbsoftinstall_log
  when: inventory_hostname in groups['primary']
  # when: inventory_hostname in groups['ora_x1']


- name: Output from Post Database Software Installation Check
  debug:
    var: racdbsoftinstall_log.stdout
    verbosity: 0
  when: inventory_hostname in groups['primary'] and "'Successfully Setup Software.' or 'Successfully Setup Software with warning(s).' in racdbsoftinstall_log.stdout"
  # when: inventory_hostname in groups['ora_x1'] and "'Successfully Setup Software.' or 'Successfully Setup Software with warning(s).' in racdbsoftinstall_log.stdout"


# [oracle@rk8-oracle02 oracle]$ sh install-rac.sh
# Launching Oracle Database Setup Wizard...
#
# [FATAL] [INS-35354] The system on which you are attempting to install Oracle RAC is not part of a valid cluster.
# CAUSE: Before you can install Oracle RAC, you must install Oracle Grid Infrastructure (Oracle Clusterware and Oracle ASM) on all servers to create a cluster.
# ACTION: Oracle Grid Infrastructure for Clusterware is not installed. Install it either from the separate installation media included in your media pack, or install it by downloading it from Electronic Product Delivery (EPD) or the Oracle Technology Network (OTN). Oracle Grid Infrastructure normally is installed by a different operating system user than the one used for Oracle Database. It may need to be installed by your system administrator. See the installation guide for more details.

