mprac1.localdomain@grid:+ASM1:/home/grid/.ssh> cat *.pub >> authorized_keys
mprac1.localdomain@grid:+ASM1:/home/grid/.ssh> scp authorized_keys mprac2:~/.ssh/
The authenticity of host 'mprac2 (192.168.45.202)' can't be established.
ECDSA key fingerprint is SHA256:da+T4x2FNHO9O+wgULy9DFf/ESx85SLTUNq/q2dw/qo.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'mprac2,192.168.45.202' (ECDSA) to the list of known hosts.
grid@mprac2's password: 
authorized_keys                                                100% 1190   813.6KB/s   00:00    
mprac1.localdomain@grid:+ASM1:/home/grid/.ssh>



