---
- name: Empty File
  shell: |
    echo "" > /lib/udev/rules.d/99-iscsidevices.rules
  register: empty_file


- name: Configure UDEV
  shell:
    cmd: |
      ISCSI_ID=$(/lib/udev/scsi_id -g -u -d /dev/{{ item.iscsi_dev }})
      cat << EOF >> /lib/udev/rules.d/99-iscsidevices.rules
      KERNEL=="sd?1", SUBSYSTEM=="block", PROGRAM=="/lib/udev/scsi_id -g -u -d /dev/\$parent", RESULT=="$ISCSI_ID", SYMLINK+="rac/{{ item.rac_dev }}", OWNER="grid", GROUP="asmadmin", MODE="0660"
      EOF
  register: config_udev
  with_items: "{{ _iscsi.target.disks }}"
- debug: msg={{ config_udev }}

- import_tasks: ext/reboot-hosts.yml

