---
- name: Waiting for Server to Come Back after Restart
  local_action: wait_for host={{ hostvars[inventory_hostname].ansible_ssh_host }} port=22 state=started delay=50 timeout=200 connect_timeout=200 search_regex=OpenSSH
  become: no


- name: Restart System
  shell: ( /bin/sleep 5 ; shutdown -r now "Ansible updates triggered" ) &
  async: 30
  poll: 0

