---
- name: Enable Autostart of Oracle Database Instances
  become_user: "{{ _oracle.root_user }}"
  shell: |
    sed -i 's/:N$/:Y/g' /etc/oratab
  register: modify_oratab
- debug: msg={{ modify_oratab }}


- name: Enable Oracle Managed File (OMF) and Autostart of Pluggable Database with the Startup of Container Database
  become_user: "{{ _oracle.user }}"
  shell: |
    source ~/.bashrc && {{ _oracle.home_dir }}/bin/sqlplus '/ as sysdba' @{{ _oracle.home_dir }}/enable-omf-autostart.sql
  register: enable_omf_autostart
- debug: msg={{ enable_omf_autostart }}
  # sqlplus -S dbuser/dbpasswd@dbsid @scriptname </dev/null

