---
- name: Check OS ( Oracle )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: prepare, install, uninstall, add, setup, remove, config, create, delete, start, stop, copy, change, enable, disable, deinstall


- name: Prepare OS Environment for Oracle Database
  import_tasks: 01-prepare-os.yml
  tags: prepare, install
  when: ( os is defined and os == true ) or ( oracle_all is defined and oracle_all == true )


- name: Install Dependent Packages
  import_tasks: 02-install-deps-pkgs.yml
  tags: setup, install
  when: ( pkgs is defined and pkgs == true ) or ( oracle_all is defined and oracle_all == true )


- name: Create Addtional Swap Space
  import_tasks: ext/make-ext-swap.yml
  tags: create, install
  when: ( swap is defined and swap == true ) or ( oracle_all is defined and oracle_all == true )


- name: Prepare Oracle Database Environment
  import_tasks: 03-prepare-oracle.yml
  tags: prepare, install
  when: ( db is defined and db == true ) or ( oracle_all is defined and oracle_all == true )


- name: Setup Oracle Database Software
  import_tasks: 04-setup-oracle.yml
  tags: setup, install
  when: ( db is defined and db == true ) or ( oracle_all is defined and oracle_all == true )


- name: Tune Init Ora Parameters
  import_tasks: ext/tune-init-ora.yml
  tags: config, install
  when: ( ora is defined and ora == true ) or ( oracle_all is defined and oracle_all == true )


- name: Deploy Oracle Database
  import_tasks: 05-deploy-oracle.yml
  tags: deploy, install
  when: ( db is defined and db == true ) or ( oracle_all is defined and oracle_all == true )


- name: Configure Oracle Database
  import_tasks: 06-config-oracle.yml
  tags: config, install
  when: ( db is defined and db == true ) or ( oracle_all is defined and oracle_all == true )


- name: Create Multi Tenant Oracle Database
  import_tasks: 07-create-multi-tenant-db.yml
  tags: create, install
  when: ( db is defined and db == true ) or ( oracle_all is defined and oracle_all == true )


- name: Delete Init Ora Parameters
  import_tasks: ext/rollback-init-ora.yml
  tags: remove, delete, install
  when: ( ora is defined and ora == true ) or ( oracle_all is defined and oracle_all == true )


- name: Copy Query Examples
  import_tasks: 08-copy-query-examples.yml
  tags: copy, install
  when: ( examples is defined and examples == true ) or ( oracle_all is defined and oracle_all == true )


- name: Enable OMF Autostart
  import_tasks: 09-enable-autostart.yml
  tags: enable, install
  when: ( omf is defined and omf == true ) or ( oracle_all is defined and oracle_all == true )


- name: Create Users
  import_tasks: 10-create-users.yml
  tags: create, add, install
  when: ( users is defined and users == true ) or ( oracle_all is defined and oracle_all == true )


- name: Enable Remote Connect
  import_tasks: 11-enable-remote-connect.yml
  tags: enable, install
  when: ( remote is defined and remote == true ) or ( oracle_all is defined and oracle_all == true )


- name: Deinstall Oracle Database
  import_tasks: 41-deinstall-oracle.yml
  tags: deinstall, unintall
  when: ( db is defined and db == true ) or ( oracle_all is defined and oracle_all == true )


- name: Disable Addtional Swap Space
  import_tasks: ext/delete-ext-swap.yml
  tags: disable, uninstall
  when: ( swap is defined and swap == true ) or ( oracle_all is defined and oracle_all == true )


- name: Uninstall Oracle Database
  import_tasks: uninstall.yml
  tags: uninstall
  when: ( oracle_all is defined and oracle_all == true )


- name: Upgrade Oracle Database
  import_tasks: upgrade.yml
  tags: upgrade
  when: ( db is defined and db == true ) or ( oracle_all is defined and oracle_all == true )


- name: Force Uninstall Oracle Database
  import_tasks: ext/force-uninstall-oracle.yml
  tags: delete, uninstall
  when: ( force is defined and force == true )


- name: Start Oracle Database
  import_tasks: ext/start-oracle.yml
  tags: start
  when: ( db is defined and db == true )


- name: Stop Oracle Database
  import_tasks: ext/stop-oracle.yml
  tags: stop
  when: ( db is defined and db == true )

