---
#--------------------------------------------------------------------------------------------
# Stop and Disable Firewall
#--------------------------------------------------------------------------------------------

- name:                 "Disable Firewall for Oracle 21c Grid Infrastructure Installation"
  block:

  - name:               "Stop and Disable Firewalld"
    service:
      name:             firewalld
      enabled:          no
      state:            stopped

  become:               yes
  become_user:          root
  # tags:                 disable_firewall

