---
#
- name: Creating installation directories
  file:
    path="{{ item }}"
    state=directory
    mode=0755
  with_items:
    - "{{ oracle_inventory }}"
    - "{{ oracle_base }}"
    - "{{ stage_dir }}"
    - "{{ oracle_home }}"
    - "{{ sub_root_directory }}"
    - "{{ sub_oradata }}"
  when: inventory_hostname in groups['databases']

- name: Create groups for Oracle Installation
  group:
    name: "{{ item.group }}"
    state: present
    gid: "{{ item.gid }}"
  loop: "{{ oracle_install_group }}"
  when: inventory_hostname in groups['databases']

- name: Set fact for oracle group list except oinstall group
  set_fact:
    oracle_group_list: "{{ oracle_install_group | selectattr('group', 'defined') | map(attribute='group') | reject('search','oinstall') | join(',') }}"

- name: Add users belonging to oinstall and {{ oracle_group_list }} group
  user:
    name: "{{ oracle_user }}"
    group: "oinstall"
    groups: "{{ oracle_group_list }}"
    state: present
    append: yes
    password: "{{ '{{ oracle_password }}' | password_hash('sha512') }}"

- name: Changing  ownership, group and permissions
  file:
    path: "{{ item }}"
    owner: oracle
    group: oinstall
    mode: '0755'
  with_items:
    - "{{ oracle_inventory }}"
    - "{{ oracle_base }}"
    - "{{ stage_dir }}"
    - "{{ oracle_home }}"
    - "{{ root_directory }}"
    - "{{ sub_root_directory }}"
    - "{{ sub_oradata }}"

#
- name: Copy .bashrc into Oracle home directory
  template: src=bashrc.j2 dest=/home/oracle/.bashrc owner=oracle group=oinstall mode=644 force=yes
  register: oracle_bashrc_copied
