---
#
- name: Check if Oracle Database Software already exists
  stat: path=/home/oracle/{{ oracle_binary }}
  register: oracle_bin_exist

#
- name: Copy Oracle Database software from Source to Target hosts
  copy: src={{ oracle_binary }} dest=/home/oracle mode=0777
  when: oracle_bin_exist.stat.exists != True

#
- name: Check if any version of Oracle Database is already unpacked
  stat: path=/u01/app/oracle/product/{{ oracle_version }}/dbhome_1
  register: oracle_unpacked

#
- name: Unpack Oracle Database Software to the target server
  unarchive:
    src: /home/oracle/{{ oracle_binary }}
    dest: /u01/app/oracle/product/{{ oracle_version }}/dbhome_1
    remote_src: yes
  when: oracle_unpacked.stat.exists == True

