---
- name: Change Password of Internal Admin Users such as Sys and System User
  become_user: "{{ _oracle.user }}"
  shell: |
    source ~/.bashrc && {{ _oracle.home_dir }}/bin/sqlplus '/ as sysdba' @{{ _oracle.home_dir }}/change-password-system.sql
  register: change_password_sys_system
- debug: msg={{ change_password_sys_system }}


- name: Create Oracle User with Password and Grant Privileges / Check Connections By Sys and System User
  become_user: "{{ _oracle.user }}"
  shell: |
    source ~/.bashrc && {{ _oracle.home_dir }}/bin/sqlplus system/changeme @{{ _oracle.home_dir }}/create-oracleuser.sql
  register: create_oracle_user
- debug: msg={{ create_oracle_user }}


- name: Connect with Oracle User and Create Table, Insert Data
  become_user: "{{ _oracle.user }}"
  shell: |
    source ~/.bashrc && {{ _oracle.home_dir }}/bin/sqlplus oracleuser/changeme @{{ _oracle.home_dir }}/create-user-table.sql
  register: connect_oracle_user
- debug: msg={{ connect_oracle_user }}

