---
- name: Copy Template of CMAN, Listener and Tnsnames for Remote Connection
  become_user: "{{ _oracle.user }}"
  template: src={{ item.fn }}.j2 dest={{ item.copy_dir }}/{{ item.fn }} owner=oracle group=oinstall mode=0644 force=yes
  register: copy_remote_connection_templates
  with_items:
    - { fn: "cman.ora", copy_dir: "{{ _oracle.home_dir }}/network/admin" }
    - { fn: "listener.ora", copy_dir: "{{ _oracle.home_dir }}/network/admin" }
    - { fn: "tnsnames.ora", copy_dir: "{{ _oracle.home_dir }}/network/admin" }
- debug: msg={{ copy_remote_connection_templates }}


- name: Restart Oracle Database Service
  become_user: "{{ _oracle.root_user }}"
  systemd:
    name: dbora
    state: restarted
  register: restart_dbora_service
  until: restart_dbora_service is succeeded
  retries: 5
  delay: 20
- debug: msg={{ restart_dbora_service }}


- name: Check if Remote Connection is Working by Using SQLPlus Command
  become_user: "{{ _oracle.user }}"
  shell: |
    source ~/.bashrc && echo 'select 1 from dual;' | {{ _oracle.home_dir }}/bin/sqlplus oracleuser/changeme@cdb1
  register: check_remote_connection
- debug: msg={{ check_remote_connection }}
  # shell: source ~/.bashrc && echo 'select 1 from dual;' | {{ _oracle.home_dir }}/bin/sqlplus oracleuser/changeme
  # shell: source ~/.bashrc && {{ _oracle.home_dir }}/bin/sqlplus oracleuser/changeme@cdb1


- name: Grant All Privileges to Oracleuser
  become_user: "{{ _oracle.user }}"
  shell: |
    source ~/.bashrc && {{ _oracle.home_dir }}/bin/sqlplus '/ as sysdba' @{{ _oracle.home_dir }}/grant-all-priv-oracleuser.sql
  register: grant_all_privileges_oracleuser
- debug: msg={{ grant_all_privileges_oracleuser }}

