---
#===============================================================================================================
# Summary Step:
# (1) Create RECO diskgroup if not exist
#===============================================================================================================

- name: Get RECO Disk Group Status
  remote_user: "{{ root_user }}"
  become_user: "{{ grid_user }}"
  shell: |
    export GRID_HOME={{ grid_home }}
    {{ grid_home }}/bin/srvctl status diskgroup -g {{ recodiskgroup }}
  register: recodgexist
  failed_when: recodgexist.rc >= 2
  ignore_errors: yes
  when: inventory_hostname in groups['primary']


- debug:
    var: recodgexist
    verbosity: 2
  when: inventory_hostname in groups['primary']


- name: Show Result if Disk Group {{ recodiskgroup }} - Exist and Already up
  debug:
    msg: "{{ recodgexist.stdout_lines }}"
  ignore_errors: yes
  when: inventory_hostname in groups['primary'] and recodgexist.stdout.find('does not exist') != 1


- name: Create RECO Diskgroups - Exit if Exist
  remote_user: "{{ root_user }}"
  become_user: "{{ grid_user }}"
  shell: "{{ stage_dir }}/createdg_reco.sh"
  register: credgtstat
  ignore_errors: yes
  when: inventory_hostname in groups['primary'] and recodgexist.stdout.find('does not exist') != 1 


- name: "Output from RECO DG Creation"
  debug:
    var: credgtstat.stdout_lines
  when: inventory_hostname in groups['primary']

