---
#=============================================================================================================================================
# Summary Steps:
# (1) Create required directories
# (2) Create a silent response file from template to create a RAC database
# (3) Create necessary templates for creating a RAC database
#=============================================================================================================================================

- name: Create Required Directories
  remote_user: "{{ root_user }}"
  file:
    path="{{ item }}"
    state=directory
    owner="{{ oracle_user }}"
    group="{{ oracle_install_group }}"
    mode=0775
  with_items:
    - "{{ stage_dir }}"
    - "{{ dbfile_path }}"


- name: Create a New File for Testing
  remote_user: "{{ root_user }}"
  # become: yes
  become_user: "{{ oracle_user }}"
  file:
    dest: "{{ oracle_home }}/dbs/init{{ oracle_sid }}1.ora"
    state: touch
  when: inventory_hostname in groups['primary']


- name: Create a Silent Database Response file
  remote_user: "{{ root_user }}"
  become_user: "{{ oracle_user }}"
  template: src=dbrac21c_rsp.j2 dest={{ stage_dir }}/dbrac21c.rsp owner=grid group=oinstall mode=0775
  register: silent_racdbsrpfile
  when: inventory_hostname in groups['primary']
  # template: src=dbrac21c_rsp.j2 dest={{ stage_dir }}/dbrac21c.rsp owner=oracle group=oinstall mode=0775


- name: Upload Template for Compatiable
  remote_user: "{{ root_user }}"
  template: src=setup_compatible.sh.j2 dest={{ stage_dir }}/setup_compatible.sh mode=0775 owner="{{ oracle_user }}" group="{{ oracle_install_group }}" force=yes 
  when: inventory_hostname in groups['primary']


- name: Upload Template for Create Password File
  remote_user: "{{ root_user }}"
  template: src=orapwd.sh.j2 dest={{ stage_dir }}/orapwd.sh mode=0775 owner="{{ oracle_user }}" group="{{ oracle_install_group }}" force=yes 
  when: inventory_hostname in groups['primary']


- name: Upload Template for DB Createfile
  remote_user: "{{ root_user }}"
  template: src=check_spfile_path.sh.j2 dest={{ stage_dir }}/check_spfile_path.sh mode=0775 owner="{{ oracle_user }}" group="{{ oracle_install_group }}" force=yes 
  when: inventory_hostname in groups['primary']


- name: Upload Template for Spfile Information
  remote_user: "{{ root_user }}"
  template: src=setup_spfile.sh.j2 dest={{ stage_dir }}/setup_spfile.sh mode=0775 owner="{{ oracle_user }}" group="{{ oracle_install_group }}" force=yes 
  when: inventory_hostname in groups['primary']


- name: Upload Template for Remote Listener File
  remote_user: "{{ root_user }}"
  template: src=silent-lsnr21c-config.rsp.j2 dest={{ stage_dir }}/setup_remlsnr.sh mode=0775 owner="{{ oracle_user }}" group="{{ oracle_install_group }}" force=yes 
  when: inventory_hostname in groups['primary']


- name: Upload Template for Setup Silent Reco Diskgroup Config Script
  remote_user: "{{ root_user }}"
  template: src=createdg_reco.sh.j2 dest={{ stage_dir }}/createdg_reco.sh mode=0775 owner="{{ grid_user }}" group="{{ oracle_install_group }}" force=yes 
  when: inventory_hostname in groups['primary']

