---
- name: Stop and Disable iSCSI Target
  systemd:
    name: target
    state: stopped
    enabled: no
    daemon-reload: yes
  register: stop_scsi_target
  ignore_errors: true
- debug: msg={{ stop_scsi_target }}


#- name: Disallow iSCSI Target Service Port
#  firewall-cmd --remove-service=iscsi-target --permanent


#- name: Reload Firewalld
#  firewall-cmd --reload


- name: Uninstall iSCSI Target and Relevant Packages
  package:
    name: "{{ item }}"
    state: absent
  register: uninstall_iscsi_pkgs
  ignore_errors: true
  with_items:
    - "target"
    - "target-restore"
    - "policycoreutils-python-utils"
- debug: msg={{ uninstall_iscsi_pkgs }}


- name: Delete vDisk Files of TGTd
  file:
    path: "{{ item.base_dir }}/{{ item.name }}.img"
    state: absent
  register: delete_disk_images
  ignore_errors: true
  with_items: "{{ _iscsi.target.disks }}"
- debug: msg={{ delete_disk_images }}


- name: Delete Directory
  file:
    path: "{{ item.base_dir }}"
    state: absent
  register: delete_dir
  ignore_errors: true
  with_items: "{{ _iscsi.target.disks }}"
- debug: msg={{ delete_dir }}


- name: Uninstall TargetCLI
  package:
    name: targetcli
    state: absent
  register: uninstall_targetcli
  ignore_errors: true
- debug: msg={{ uninstall_targetcli }}
  when: print_debug == true


- name: Delete Config Files of TargetCLI
  file:
    path: "{{ item }}"
    state: absent
  register: delete_config_files
  ignore_errors: true
  with_items:
    - "/etc/target"
- debug: msg={{ delete_config_files }}

