---
#==========================================================================================================
# (1) Install Oracle GI 21.3.0 executeConfigTools in Silent Mode
# (2) Validate output logs 
#==========================================================================================================

- name: Setup Oracle 21c Grid Infrastructure ConfigTools in Silent Mode
  remote_user: "{{ root_user }}"
  become_user: "{{ grid_user }}"
  shell: |
    {{ grid_home }}/gridSetup.sh -silent -executeConfigTools -responseFile {{ stage_dir }}/{{ gi_rspfile }}
  register: racgi_configtools_result
  failed_when: racgi_configtools_result.rc != 0   #### This condition is based on my own setup
  when: inventory_hostname in groups['primary']
- debug: msg={{ racgi_configtools_result }}
  when: inventory_hostname in groups['primary']
  # args:
  #   warn: false # set warn=false to prevent warning
  # failed_when: racgi_configtools_result.rc != 255   #### This condition is based on my own setup


- name: Get the Log Information
  remote_user: "{{ root_user }}"
  shell: |
    grep -r "'UpdateNodeList' was successful *" {{ ora_inventory }}/logs/UpdateNodeList*.log
  register: configtools_log
  when: inventory_hostname in groups['primary']
- debug: msg={{ configtools_log }}
  when: inventory_hostname in groups['primary']


- debug: var=configtools_log.stdout_lines
  when: inventory_hostname in groups['primary']

