---
- name: Create Required Directories
  remote_user: "{{ root_user }}"
  file:
    path="{{ item }}"
    state=directory
    owner="{{ grid_user }}"
    group="{{ oracle_install_group }}"
    recurse=yes
    mode=0775
  with_items:
    - "{{ stage_dir }}"
    - "{{ ora_inventory }}"
    - "{{ grid_base }}"
    - "{{ grid_home }}"
    - "{{ software_dir }}"              # Added Manually
    - "/u01/app"                        # To avoid errors appeared when running root.sh
    - "/u02/app"                        # To avoid errors appeared when running root.sh
  when: inventory_hostname in groups['dbservers']

