---
#=============================================================================================================================
# Assumption:
#  -  Two separate machines ( example - Ora-X1 and Ora-x2 ) are configured
#  -  All required OS groups and users are in place
#  -  Necessay network setup is in place 
#  -  Oracle GI software is downloaded and staged
# Summary Steps
# (1) Install CVU
# (2) Unzipped Oracle Grid Infrastructure Software
# (3) Create Response File for Silent Installation
# (4) Install Oracle GI 21.3.0 Software Only in Silent Mode
# (5) Run necessay root scripts
#==============================================================================================================================


- name: Check OS ( Oracle )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: deploy, destroy, prepare, install, uninstall, add, setup, execute, remove, validate, finalize, create, delete, config, modify, pre, post


- name: Display Pre Installation of Oracle Grid Infrastructure Software Message
  debug:
    msg:
      - 'This playbook is for installing Oracle RAC GI software 21c , started at {{ansible_date_time.iso8601}}:'
  tags: pre, install
  when: ( msg is defined and msg == true ) or ( grid_all is defined and grid_all == true )


- name: Modify OS Settings
  import_tasks: modify-os-setting.yml
  tags: prepare, install
  when: ( os is defined and os == true ) or ( grid_all is defined and grid_all == true )


- name: Create Required Directories
  import_tasks: create-required-dirs.yml
  tags: create, install
  when: ( dir is defined and dir == true ) or ( grid_all is defined and grid_all == true )


- name: Setup NTP Server
  import_tasks: setup-chrony.yml
  tags: setup, install
  when: ( ntp is defined and ntp == true ) or ( grid_all is defined and grid_all == true )


- name: Prepare Oracle Grid Infrastructure Software
  import_tasks: prepare-software.yml
  tags: prepare, install
  when: (( software is defined and software == true ) or ( grid_all is defined and grid_all == true )) and inventory_hostname in groups['dbservers']


- name: Setup Oracle Grid Infraintrastructure Software
  import_tasks: setup-software.yml
  tags: setup, install
  when: ( software is defined and software == true ) or ( grid_all is defined and grid_all == true )


- name: Execute orainstRoot.sh
  import_tasks: execute-orainst-root.yml
  tags: execute, install
  when: ( orainstroot is defined and orainstroot == true ) or ( grid_all is defined and grid_all == true )


- name: Execute root.sh
  import_tasks: execute-root-sh.yml
  tags: execute, install
  when: ( root is defined and root == true ) or ( grid_all is defined and grid_all == true )


- name: Post Oracle Grid Infrastructure Installation Tasks
  import_tasks: config-tools.yml
  tags: config, install
  when: ( tools is defined and tools == true ) or ( grid_all is defined and grid_all == true )


- name: Verify Oracle Grid Cluster
  import_tasks: verify-cluster.yml
  tags: verify, install
  when: ( cluster is defined and cluster == true ) or ( grid_all is defined and grid_all == true )


- name: Delete Stage Directory
  remote_user: "{{ root_user }}"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ stage_dir }}"
    - "/u01/stage/LINUX.X64_213000_grid_home.zip"
  tags: delete, install
  when: ( stage is defined and stage == true ) or ( grid_all is defined and grid_all == true )


- name: Delete Oracle Grid Config
  import_tasks: ext/delete-grid-config.yml
  tags: delete, remove
  when: ( config is defined and config == true )


- name: Destroy Oracle Grid Service
  import_tasks: destroy-grid-service.yml
  tags: destroy, uninstall
  when: ( service is defined and service == true ) or ( grid_all is defined and grid_all == true )


- name: Display Post Install Message
  debug:
    msg:
      - 'This Steps completed below task for Single Instance at {{ansible_date_time.iso8601}}:'
      - '- Install Oracle Grid Infrastructure 21c on two node RAC cluster rk8-oracle01 and rk8-oracle02 and rk8-oracle03'
      - '- END OF ALL: git repository GI_21cSoftInstall will be shared'
  tags: post, install
  when: ( msg is defined and msg == true ) or ( grid_all is defined and grid_all == true )

