---
#===========================================================================================
# (1) Assumption: Oracle GI software is downloaded and staged
# (2) modify settings for OS
#===========================================================================================

- name: Change SELinux is Disable
  lineinfile: dest=/etc/selinux/config create=no insertafter=EOF line='SELINUX=disabled'


- name: Stop Firewall
  shell: systemctl stop firewalld


- name: Stop Auto Start  Firewall
  shell: systemctl disable firewalld


- name: Stop Auto Start a Chronyd
  shell: systemctl disable chronyd


- name: Stop Chronyd
  shell: systemctl stop chronyd


- name: Backup /etc/hosts
  shell: cp -p /etc/hosts /etc/hosts.`date +%Y%m%d`


- name: Backup /etc/sysctl.conf
  shell: cp -p /etc/sysctl.conf /etc/sysctl.conf.`date +%Y%m%d%H%M%S`

