---
#========================================================================================================
# (1) Install Oracle GI 21.3.0 Software Only in Silent Mode
# (2) Validate output logs 
#========================================================================================================

- name: Setup Oracle 21c Grid Infrastructure Software
  remote_user: "{{ root_user }}"
  become_user: "{{ grid_user }}"
  shell: |
    {{ grid_home }}/gridSetup.sh -silent -ignorePrereqFailure -waitforcompletion \
    -skipStackCheck -responseFile {{ stage_dir }}/{{ gi_rspfile }} > /u02/stage/giinstalloutput.log
  register: racgisoft_install_result
  failed_when: racgisoft_install_result.rc != 6   #### This condition is based on my own setup
  # ignore_errors: true
  when: inventory_hostname in groups['primary']
  # no_log: true
  # no_log: false
  # args:
  #   warn: false # set warn=false to prevent warning


- name: Get the Output Log Status
  remote_user: "{{ root_user }}"
  become_user: oracle
  shell: grep -r "Successfully Setup Software with *" /u02/stage/giinstalloutput.log
  register: racgisoftinstall_log
  ignore_errors: true
  when: inventory_hostname in groups['primary']


- name: Output from Post GI Software Installation Check
  debug:
    var: racgisoftinstall_log.stdout
    verbosity: 0
  when: inventory_hostname in groups['primary'] and "'Successfully Setup Software.' or 'Successfully Setup Software with warning(s).' in racgisoftinstall_log.stdout"


