---
#========================================================================================
# (1) Add oratab entry for ASM instances
# (2) Validate Oracle GI Cluster Resources
#========================================================================================

- name: Add Oratab Entry to First Node
  remote_user: "{{ root_user }}"
  lineinfile: dest=/etc/oratab line="{{ asmi }}1:{{ grid_home }}:Y" state=present
  when: inventory_hostname in groups['primary']


- name: Add Oratab Entry to Second Node
  remote_user: "{{ root_user }}"
  lineinfile: dest=/etc/oratab line="{{ asmi }}2:{{ grid_home }}:Y" state=present
  when: inventory_hostname in groups['secondary']


- name: Check CRS Resources and Status
  remote_user: "{{ root_user }}"
  become_user: "{{ grid_user }}"
  shell: "{{ grid_home }}/bin/crsctl stat res -t"
  register: crsctl_resstat
  when: inventory_hostname in groups['primary']


- debug: var=crsctl_resstat.stdout_lines
  when: inventory_hostname in groups['primary']


- name: Check Cluster Status
  remote_user: "{{ root_user }}"
  become_user: "{{ grid_user }}"
  shell: "{{ grid_home }}/bin/crsctl check cluster -all"
  register: cluster_stat
  when: inventory_hostname in groups['primary']


- debug: var=cluster_stat.stdout_lines
  when: inventory_hostname in groups['primary']


- name: Check ASM Cluster Mode
  remote_user: "{{ root_user }}"
  become_user: "{{ grid_user }}"
  action: shell export GRID_HOME={{ grid_home }}; {{ grid_home }}/bin/asmcmd showclustermode
  register: asmcluster_mode
  when: inventory_hostname in groups['primary']


- debug: var=asmcluster_mode.stdout_lines
  when: inventory_hostname in groups['primary']


- name: Ensure Bash Profile File Exists
  copy:
    content: ""
    dest: /home/grid/.bash_profile
    force: no
    group: sys
    owner: root
    mode: 0555


- name: Bash Profile for Root, Oracle, Grid Users
  blockinfile:
    path: "{{ item }}/.bash_profile"
    insertafter: '#### For {{ item }} #####'
    state: present
    block: |
      export PATH=$PATH:$HOME/bin
      export PATH=/usr/bin:$PATH
      export LD_LIBRARY_PATH=/usr/lib:/lib
      export NLS_LANG=AMERICAN_AMERICA.UTF8
      export NLS_DATE_FORMAT='DD-MM-YYYY:HH24:MI:SS'
      export ORACLE_BASE="{{ grid_base }}"
      export ORACLE_HOME="{{ grid_home }}"
      export PATH=$ORACLE_HOME/bin:$PATH
      alias sqlss='sqlplus / as sysdba'
      alias chob="cd ${ORACLE_BASE}"
      alias choh="cd ${ORACLE_HOME}"
  with_items:
    - "/root"
    - "/home/oracle"
    - "/home/grid"


- name: Set File Permissions
  file:
    path: "{{ item.dir }}/.bash_profile"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0644"
  with_items:
    - { owner: "root",   group: "root",     dir: "/root" }
    - { owner: "oracle", group: "oinstall", dir: "/home/oracle" }
    - { owner: "grid",   group: "oinstall", dir: "/home/grid" }

