---
- name: Check OS ( Hosts )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when:
    - ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'
    - inventory_hostname in groups['servers']


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: init, uninit, install, uninstall
  when: inventory_hostname in groups['servers']


- name: Setup Hostname and IP Address in /etc/hosts
  import_tasks: init-hosts.yml
  tags: init, install
  when: inventory_hostname in groups['servers']


- name: Install Prerequiestes Software Packages and Setup Hostname, IP Addresses
  import_tasks: install.yml
  tags: init, install
  when: inventory_hostname in groups['servers']


- name: Create SSH Key and Exchange It for Sudo User among All Hosts
  import_tasks: ssh_sudo_user.yml
  tags: init, install
  when: inventory_hostname in groups['servers']


- name: Create SSH Key and Exchange It for Root User among All Hosts
  import_tasks: ssh_root_user.yml
  tags: init, install
  when: inventory_hostname in groups['servers']


- name: Add Oracle Groups and Users
  import_tasks: add-oracle-users.ynml
  tags: init, install
  when: inventory_hostname in groups['servers']


- name: Create SSH Key and Exchange It for Oracle User among All Hosts
  import_tasks: ssh_oracle_user.yml
  tags: init, install
  when: inventory_hostname in groups['servers']


- name: Create SSH Key and Exchange It for Grid User among All Hosts
  import_tasks: ssh_grid_user.yml
  tags: init, install
  when: inventory_hostname in groups['servers']


- name: Uninstall SSH Keys and Sudo Users as well as Prerequiestes Software Packages
  import_tasks: uninstall.yml
  tags: uninit, uninstall
  when: inventory_hostname in groups['servers']

