---
- name: Remove Hostname Entries In /etc/hosts File
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ domain_name }}"
    line: "{{ _ipaddr }}"
    state: absent
    backup: yes
  register: hosts_deleted
  when: _ipaddr is defined
  with_items: "{{ groups['all'] }}"


- name: Kill Processes Hold On User Directory
  become: true
  shell: |
    {{ item }}
    sleep 3
  register: kill_user_processes
  until: kill_user_processes is succeeded
  retries: 5
  with_items:
    - "nohup pkill -U {{ sudo_user }}"
    - "nohup fuser -k /home/{{ sudo_user }}"
    - "nohup pkill -U {{ oracle_user }}"
    - "nohup fuser -k /home/{{ oracle_user }}"
    - "nohup pkill -U {{ grid_user }}"
    - "nohup fuser -k /home/{{ grid_user }}"


- name: Delete "{{ sudo_user }}" User and Group
  user:
    name: "{{ sudo_user }}"
    group: "{{ sudo_group }}"
    state: absent


- name: Delete Users Belonging to Oinstall Group and Install Groups
  user:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ oracle_user }}"
    - "{{ grid_user }}"


- name: Delete Groups
  group:
    name: "{{ item.group }}"
    state: absent
    gid: "{{ item.gid }}"
  loop: "{{ _oracle.install_group }}"


- name: Rollback Default Group to /etc/sudoers File
  become_user: root
  lineinfile:
    dest: /etc/sudoers
    state: absent
    regexp: '^%{{ item }}'
    line: '%{{ item }}  ALL=(ALL)        ALL'
  with_items:
    - "{{ sudo_user }}"
    - "{{ oracle_user }}"
    - "{{ grid_user }}"


- name: Remove bash_history and .ssh Directory
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/root/.bash_history"
    - "/home/{{ sudo_user }}/.bash_history"
    - "/home/{{ oracle_user }}/.bash_history"
    - "/home/{{ grid_user }}/.bash_history"
    - "/root/.ssh"
    - "/home/{{ sudo_user }}/.ssh"
    - "/home/{{ oracle_user }}/.ssh"
    - "/home/{{ grid_user }}/.ssh"
    - "/home/{{ sudo_user }}"
    - "/home/{{ oracle_user }}"
    - "/home/{{ grid_user }}"


- name: Uninstall Prerequest Software Packages
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ install_pkgs }}"
  when: uninstall_deps_pkgs == true


- name: Disable Development Package Repository for RedHat Based Linux Distribution
  shell: |
    yum-config-manager --disable {{ item }}
  with_items:
    - "devel"
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky"

