---
- name: Start Oracle Listener
  become_user: "{{ _oracle.user }}"
  shell: |
    source ~/.bashrc && {{ _oracle.home_dir }}/bin/lsnrctl start
  register: start_oracle_listener
- debug: msg={{ start_oracle_listener }}


- name: Start and Enable Oracle Database Service
  become_user: "{{ _oracle.root_user }}"
  systemd:
    name: dbora
    state: started
    enabled: yes
    daemon_reload: yes
  register: start_dbora_service
  until: start_dbora_service is succeeded
  retries: 5
  delay: 20
- debug: msg={{ start_dbora_service }}

