---
# =============================================================================
# Install Oracle Grid Infrastructure (GI) 21.3.0 Software Only:
# Assumption:
#  -  Two separate machines ( example - Ora-X1 and Ora-x2 ) are configured
#  -  All required OS groups and users are in place
#  -  Necessay network setup is in place 
#  -  Oracle GI software is downloaded and staged
# Summary Steps - 
# (1) Install CVU 
# (2) Unzipped Oracle GI software 
# (3) Create response file for silent installation
# (4) Install Oracle GI 21.3.0 Software Only in Silent Mode
# (5) Run necessay root scripts
# =============================================================================


#- name: Display Pre Installation of Oracle Grid Infrastructure Software Message
#  debug:
#    msg:
#      - 'This playbook is for installing Oracle RAC GI software 21c , started at {{ansible_date_time.iso8601}}:'


- name: Check OS ( Oracle )
  fail: msg="Not a Red Hat based system!"
  when: ansible_os_family != 'RedHat' or ansible_os_family != 'CentOS' or ansible_os_family != 'Rocky'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-facts.yml
  tags: prepare, install, uninstall, add, setup, execute, remove, validate, finalize, create, delete


- name: Modify OS Settings
  import_tasks: modify-os-setting.yml
  tags: prepare
  when: ( os is defined and os == true ) or ( racgi_all is defined and racgi_all == true )


- name: Modify Oracle Settings
  import_tasks: modify-oracle-setting.yml
  tags: prepare
  when: ( oracle is defined and oracle == true ) or ( racgi_all is defined and racgi_all == true )


- name: Add Group and Users
  import_tasks: 00-add-users.yml
  tags: add
  when: ( user is defined and user == true ) or ( racgi_all is defined and racgi_all == true )
  # import_tasks: oracle-userngroup.yml


- name: Create Required Directories
  import_tasks: create-required-dirs.yml
  tags: create
  when: ( dir is defined and dir == true ) or ( racgi_all is defined and racgi_all == true )


- name: Setup NTP Server
  import_tasks: setup-chrony.yml
  tags: setup
  when: ( ntp is defined and ntp == true ) or ( racgi_all is defined and racgi_all == true )
  # import_tasks: install-ntp.yml


- name: Preparation Tasks for Installing Oracle Grid Infrastructure Software
  import_tasks: prepare-software.yml
  tags: prepare
  when: ( software is defined and software == true ) or ( racgi_all is defined and racgi_all == true )


- name: Install Oracle Grid Infraintrastructure Software Using Ansible
  import_tasks: install-software.yml
  tags: setup
  when: ( software is defined and software == true ) or ( racgi_all is defined and racgi_all == true )


- name: Install Oracle Grid Infraintrastructure Software Using Ansible
  import_tasks: setup-oinsroot.yml
  tags: setup
  when: ( oinsroot is defined and oinsroot == true ) or ( racgi_all is defined and racgi_all == true )


- name: Install Oracle Grid Infraintrastructure Software Using Ansible
  import_tasks: setup-root.yml
  tags: setup
  when: ( root is defined and root == true ) or ( racgi_all is defined and racgi_all == true )


- name: Post Oracle Grid Infrastructure Installation Tasks
  import_tasks: config-tools.yml
  tags: config
  when: ( tools is defined and tools == true ) or ( racgi_all is defined and racgi_all == true )


- name: Finalize Software
  import_tasks: post-install.yml
  tags: finalize
  when: ( software is defined and software == true ) or ( racgi_all is defined and racgi_all == true )


- name: Remove Stage Directory
  remote_user: "{{ root_user }}"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ stage_dir }}"
  tags: remove
  when: ( stage is defined and stage == true ) or ( racgi_all is defined and racgi_all == true )


# - name: Display Post Install Message
#  debug:
#    msg:
#      - 'This Steps completed below task for Single Instance at {{ansible_date_time.iso8601}}:'
#      - '- Install Oracle Grid Infrastructure 21c on two node RAC cluster ora_x1 and ora_x2'
#      - '- END OF ALL: git repository GI_21cSoftInstall will be shared'


