---
# =============================================================================
# Install Oracle GI 21.3.0 Software Only:
# (1) Assumption: Oracle GI software is downloaded and staged
# (2) Install cluster verification utility
# (3) Unpack Oracle GI software to the Oracle Home directory into the first node
# (4) Run cluster Verification Checks for CRS Installation
# =============================================================================

- name: Copy Grid 21c Grid Software Response File to the Target Database Server
  remote_user: "{{ root_user }}"
  copy: src=templates/{{ item }} dest={{ stage_dir }} owner=grid group=oinstall mode=0775
  with_items:
    - gridsetup21c.rsp

  # tags:
  #  - gisoftinstall_cprspfile
  #  - oracle-database-preinstall-21c-1.0-1.el7.x86_64.rpm


- name: Copy Database Pre Install 21c RPM Pfile to the Target Database Server
  remote_user: "{{ root_user }}"
  copy: src={{ item.fn }} dest={{ item.dest }} owner=grid group=oinstall mode=0775
  with_items:
    - { dest: "{{ stage_dir }}" ,    fn: "oracle-database-preinstall-21c-1.0-1.el8.x86_64.rpm" }
    - { dest: "{{ software_dir }}", fn: "LINUX.X64_213000_grid_home.zip" }


- name: Unpack Oracle 21c GI Software
  remote_user: "{{ root_user }}"
  become: yes
  become_user: "{{ grid_user }}"
  unarchive:
     src={{ software_dir }}/LINUX.X64_213000_grid_home.zip
     dest="{{ grid_home }}"
     mode=0775
     group="{{ oracle_install_group }}"
     owner="{{ grid_user }}"
     remote_src=yes
  when: inventory_hostname in groups['ora_x1']

  # tags:
  # - gisoftinstall_unpacksoft


- name: Install CVU RPM from Local File
  yum:
    name: /u02/app/21.3.0/grid/cv/rpm/cvuqdisk-1.0.10-1.rpm
    state: present
    disable_gpg_check: yes
  when: inventory_hostname in groups['ora_x1']


- name: Transfer CVU File from ora_x1 to ora_x2
  synchronize:
    src: /u02/app/21.3.0/grid/cv/rpm/cvuqdisk-1.0.10-1.rpm
    dest: /u02/stage/cvuqdisk-1.0.10-1.rpm
    mode: pull
  delegate_to: rk8-oracle03
  when: inventory_hostname in groups['ora_x1']


- name: Install CVU RPM from Local File
  yum:
    name: /u02/stage/cvuqdisk-1.0.10-1.rpm
    state: present
    disable_gpg_check: yes
  when: inventory_hostname in groups['ora_x2']


- name: Run Cluster Verification Checks for CRS Installation
  become: yes
  become_user: grid
  shell: |
    {{ grid_home}}/runcluvfy.sh stage -post crsinst -n "ora_x1,ora_x2" -verbose
  register:           cluvfy_stage_pre_crsinst
  failed_when:        false
  no_log:             true
  when: inventory_hostname in groups['ora_x1']

