---
# =============================================================================
# Install Oracle GI 21.3.0 Software Only:
# (1) Execute root.sh scripts
# =============================================================================

- name: Execute root.sh on the First Node
  remote_user: "{{ root_user }}"
  become: yes
  shell: "{{ grid_home }}/root.sh"
  register: rootnode1
  tags:
    - gisoftinstall_exeroot
  when: inventory_hostname in groups['ora-x1'] 


- name: Get the Logfile Name on the First Node
  remote_user: "{{ root_user }}"
  become: yes
  shell: "echo {{ rootnode1.stdout }} | grep -oP '(?<=Check).*?(?=for)' "
  register: logfile
  when: inventory_hostname in groups['ora-x1']


- name: Get the Logfile Information on the First Node
  remote_user: "{{ root_user }}"
  become: yes
  shell: "cat {{ logfile.stdout }} "
  with_items:
    - logino.log
  args:
    chdir: /u01/app
  register: rootloginfon1
  when: inventory_hostname in groups['ora-x1']


- debug:
    var: rootloginfon1.results[0].stdout_lines
  when: inventory_hostname in groups['ora-x1']


- name: Execute root.sh on the Second Node
  remote_user: "{{ root_user }}"
  become: yes
  shell: "{{ grid_home }}/root.sh"
  register: rootnode2
  tags:
    - gisoftinstall_exeroot
  when: inventory_hostname in groups['ora-x2'] 


- name: Get the Logfile Information on the Second Node
  remote_user: "{{ root_user }}"
  become: yes
  shell: "echo {{ rootnode2.stdout }} | grep -oP '(?<=Check).*?(?=for)' "
  register: logfile
  when: inventory_hostname in groups['ora-x2']


- name: Get the logfile Information on the Second Node
  when: inventory_hostname in groups['ora-x2']
  remote_user: "{{ root_user }}"
  become: yes
  shell: "cat {{ logfile.stdout }} "
  with_items:
    - logino.log
  args:
    chdir: /u01/app
  register: rootloginfon2


- debug:
    var: rootloginfon2.results[0].stdout_lines
  when: inventory_hostname in groups['ora-x2']


