---
# =============================================================================
# (1) Add oratab entry for ASM instances
# (2) Validate Oracle GI Cluster Resources
# =============================================================================

- name: Add Oratab Entry to First Node
  remote_user: "{{ root_user }}"
  lineinfile: dest=/etc/oratab line="{{ ASMI }}1:{{ grid_home }}:Y" state=present
  when: inventory_hostname in groups['ora_x1']


- name: Add Oratab Entry to Second Node
  remote_user: "{{ root_user }}"
  lineinfile: dest=/etc/oratab line="{{ ASMI }}2:{{ grid_home }}:Y" state=present
  when: inventory_hostname in groups['ora_x2']


- name: Check CRS Resources and Status
  remote_user: "{{ root_user }}"
  become: yes
  become_user: "{{ grid_user }}"
  shell: "{{ grid_home }}/bin/crsctl stat res -t"
  register: crsctl_resstat
  when: inventory_hostname in groups['ora_x1']


- debug: var=crsctl_resstat.stdout_lines
  when: inventory_hostname in groups['ora_x1']


- name: Check Cluster Status
  remote_user: "{{ root_user }}"
  become: yes
  become_user: "{{ grid_user }}"
  shell: "{{ grid_home }}/bin/crsctl check cluster -all"
  register: cluster_stat
  when: inventory_hostname in groups['ora_x1']


- debug: var=cluster_stat.stdout_lines
  when: inventory_hostname in groups['ora_x1']


- name: Check ASM Cluster Mode
  remote_user: "{{ root_user }}"
  become: yes
  become_user: "{{ grid_user }}"
  action: shell export GRID_HOME={{ grid_home }}; {{ grid_home }}/bin/asmcmd showclustermode
  register: asmcluster_mode
  when: inventory_hostname in groups['ora_x1']


- debug: var=asmcluster_mode.stdout_lines
  when: inventory_hostname in groups['ora_x1']


- name: Ensure Bash Profile File Exists
  copy:
    content: ""
    dest: /home/grid/.bash_profile
    force: no
    group: sys
    owner: root
    mode: 0555


- name: Bash Profile for User Grid
  become: yes
  become_user: "{{ grid_user }}"
  blockinfile:
    path: /home/grid/.bash_profile
    insertafter: '#### for grid #####'
    state: present
    block: |
      export PATH=$PATH:$HOME/bin
      export PATH=/usr/bin:$PATH
      export LD_LIBRARY_PATH=/usr/lib:/lib
      export NLS_LANG=AMERICAN_AMERICA.UTF8
      export NLS_DATE_FORMAT='DD-MM-YYYY:HH24:MI:SS'
      export ORACLE_BASE="{{ grid_base }}"
      export ORACLE_HOME="{{ grid_home }}"
      export PATH=$ORACLE_HOME/bin:$PATH
      alias sqlss='sqlplus / as sysdba'
      alias chob="cd ${ORACLE_BASE}"
      alias choh="cd ${ORACLE_HOME}"


